### ISSUE TITLE
Conflict with Misc. Robots++

### ISSUE THREAD

**Issue by KyuubiYoru** [CodeOptimist/rimworld-jobs-of-opportunity#3]
Just added Jobs of opportunity and had the problem that a OmniBot from Misc. Robots++ tried to HaulToInventory and destroy the items while doing that.
I guess OmniBot's don't have an Inventory.

JobDriver threw exception in initAction for pawn OmniBot 1 driver=JobDriver_HaulToInventory (toilIndex=2) driver.job=(HaulToInventory (Job_967051) A=Thing_Steel130646 B=(82, 0, 175))
System.NullReferenceException: Object reference not set to an instance of an object
  at PickUpAndHaul.JobDriver_HaulToInventory+<>c__DisplayClass1_0.<MakeNewToils>b__2 () [0x00096] in <ac2642f61fbf46c5810ed34fcf95bf58>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001df] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
Verse.Log:DMD<DMD<Warning_Patch1>?1440368896::Warning_Patch1>(String, Boolean)
Verse.AI.JobUtility:DMD<DMD<TryStartErrorRecoverJob_Patch0>?1841142144::TryStartErrorRecoverJob_Patch0>(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:DMD<DMD<TryEnterNextPathCell_Patch0>?-697242368::TryEnterNextPathCell_Patch0>(Pawn_PathFollower)
Verse.AI.Pawn_PathFollower:PatherTick()
Verse.Pawn:DMD<DMD<Tick_Patch1>?511785472::Tick_Patch1>(Pawn)
AIRobot.X2_AIRobot:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:DMD<DMD<Update_Patch1>?1510671104::Update_Patch1>(Root_Play)

**Comment by CodeOptimist** [comment]
Looks like a compatibility issue with PUAH itself, so would ideally be fixed there, but I may end up doing something about it. Thanks for reporting this.
