### ISSUE TITLE
HugsLib+Jobs of opportunity error

### ISSUE THREAD

**Issue by ianmpl** [CodeOptimist/rimworld-jobs-of-opportunity#6]
So, I have been getting a ton of error messages and I think the cause may be jobs of opportunity...this is the error I found when loading my mod list:

[HugsLib][warn] Missing enum setting labels for enum JobsOfOpportunity.JobsOfOpportunity+Hauling+HaulProximities
Verse.Log:Verse.Log.Warning_Patch1(String, Boolean)
HugsLib.Utils.ModLogger:Warning(String, Object[])
HugsLib.Settings.ModSettingsPack:GetHandle(String, String, String, HaulProximities, ValueIsValid, String)
JobsOfOpportunity.JobsOfOpportunity:<DefsLoaded>g__GetSettingHandle|24_0(String, HaulProximities, ValueIsValid, ShouldDisplay, String)
JobsOfOpportunity.JobsOfOpportunity:DefsLoaded()
HugsLib.HugsLibController:OnDefsLoaded()
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by CodeOptimist** [comment]
Hmm I've seen this before. Thing is, those enum setting labels definitely aren't missing. Maybe it's something to do with HugsLib being interfered with. 🤔

**Comment by CodeOptimist** [comment]
Not something I can fix I don't think... mod loading issue or some other transient issue not related to JoO I believe. If I determine the exact cause I will go after it. 👍
